//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string GAME_START = "game_start";
        
        public const string AED_GETTING_SHOCKED = "aed_getting_shocked";
        
        public const string LEFT_GLOVE_PINCH = "left_glove_pinch";
        
        public const string LEFT_CPR_PRESS = "left_cpr_press";
        
        public const string RIGHT_GLOVE_PINCH = "right_glove_pinch";
        
        public const string RIGHT_CPR_PRESS = "right_cpr_press";
    }
}
